<?php
namespace Training\FiveUnit\Controller\Entity;

use Magento\Framework\App\Action\AbstractAction;
use Magento\Framework\App\Action\Context;
use Magento\Framework\App\ResponseInterface;

class Custom extends \Magento\Framework\App\Action\Action
{
    /**
     * @var \Training\FiveUnit\Api\CommentRepositoryInterface
     */
    protected $_commentRepository;

    /**
     * @var \Magento\Framework\Api\SearchCriteriaBuilder
     */
    protected $_searchCriteriaBuilder;

    public function __construct(
        Context $context,
        \Training\FiveUnit\Api\CommentRepositoryInterface $commentRepository,
        \Magento\Framework\Api\SearchCriteriaBuilder $searchCriteriaBuilder
    )
    {
        $this->_searchCriteriaBuilder = $searchCriteriaBuilder;
        $this->_commentRepository = $commentRepository;
        parent::__construct($context); // TODO: Change the autogenerated stub
    }


    /**
     * Dispatch request
     *
     * @return \Magento\Framework\Controller\ResultInterface|ResponseInterface
     * @throws \Magento\Framework\Exception\NotFoundException
     */
    public function execute()
    {
        $searchCriteria = $this->_searchCriteriaBuilder->create();
        $repository = $this->_commentRepository->getList($searchCriteria);
        $items = $repository->getItems();

        $resp = [];
        foreach ($items as $item) {
            $resp[] = $item->getTitle();
        }
        var_dump($resp);
        exit;
    }

}