<?php $orderInfo = $this->getOrderInfo(); ?>
<div class="order-info">
    <ul>
        <li><?php echo __('Order status is:') ?><?php echo $orderInfo['status']; ?></li>
        <li><?php echo __('Order total:');?><?php echo $orderInfo['total']; ?></li>
        <li><?php echo __('Order total invoiced:'); ?><?php echo $orderInfo['total_invoiced']; ?></li>
        <li><?php echo __('Items info'); ?>
            <ul>
                <?php foreach($orderInfo['items'] as $item): ?>
                    <li><?php echo $item['sku']; ?></li>
                    <li><?php echo $item['price']; ?></li>
                <?php endforeach; ?>
            </ul>
        </li>
    </ul>
</div>
