<?php
namespace Training3\OrderInfo\Controller\Action;

use Magento\Framework\App\Action\Context;
use Magento\Framework\App\ResponseInterface;
use Magento\Framework\View\Result\PageFactory;

class Info extends \Magento\Framework\App\Action\Action
{
    const ORDER_ID = 'order_id';
    /**
     * @var \Magento\Framework\Registry
     */
    protected $_coreRegistry;

    protected $_pageFactory;

    /**
     * @param Context $context
     */
    public function __construct(Context $context,
        \Magento\Sales\Model\OrderFactory $orderFactory,
        \Magento\Framework\Registry $coreRegistry,
        PageFactory $pageFactory,
        \Magento\Framework\Registry $coreRegistry
    ) {
        $this->_coreRegistry = $coreRegistry;
        $this->_pageFactory = $pageFactory;
        parent::__construct($context); // TODO: Change the autogenerated stub
    }

    /**
     * Dispatch request
     *
     * @return \Magento\Framework\Controller\ResultInterface|ResponseInterface
     * @throws \Magento\Framework\Exception\NotFoundException
     */
    public function execute()
    {
        $param = $this->getRequest()->getParam('json');
        $orderId = $this->getRequest()->getParams(self::ORDER_ID);
        if (!$param && $orderId) {
            $this->_coreRegistry->register(self::ORDER_ID, $orderId);
            $page = $this->_pageFactory->create();
            return $page;
        }
    }

}