<?php
namespace Training\SixUnit\Model;

use Magento\Framework\DataObject;
use Training\SixUnit\Api\Data\ComputerGamesInterfaceFactory;

class ComputerGames extends \Magento\Framework\Model\AbstractModel
{
    /**
     * @var \Training\SixUnit\Api\Data\ComputerGamesInterfaceFactory
     */
    protected $computerGamesDataFactory;

    /**
     * @var \Magento\Framework\Api\DataObjectHelper
     */
    protected $objectHelper;

    public function __construct(
        \Magento\Framework\Model\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Model\ResourceModel\AbstractResource $resource = null,
        \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
        array $data = [],
        \Training\SixUnit\Api\Data\ComputerGamesInterfaceFactory $computerGamesInterfaceFactory
    )
    {
        parent::__construct($context, $registry, $resource, $resourceCollection, $data); // TODO: Change the autogenerated stub
        $this->computerGamesDataFactory = $computerGamesInterfaceFactory;
    }


    protected function _construct()
    {
        $this->_init('Training\SixUnit\Model\ResourceModel\ComputerGames');
    }

    /**
     * @return mixed
     */
    public function getDataModel()
    {
        $computersData = $this->getData();
        $gamesDataObject = $this->computerGamesDataFactory->create();
        $this->objectHelper->populateWithArray(
            $gamesDataObject,
            $computersData,
            '\Training\SixUnit\Api\Data\ComputerGamesInterface'
        );
        $gamesDataObject->setGameId($this->getGameId());
        return $gamesDataObject;
    }
}
